### ISSUE TITLE
Network.network_connect() called on installer startup...

### ISSUE THREAD

**Issue by antoniovazquezblanco** [antoniovazquezblanco/ArchSetup#22]
When the program is started the window `NetworkWindow` is created and selection event gets called, triggering `self.network.network_connect(opt)` in line 52.

This should not get called until the network window is shown and the user chooses.

**Comment by mame98** [comment]
Yes, you are right, I did not notice it...

**Comment by antoniovazquezblanco** [comment]
No problem. I just don't haven't thought how I would like to solve it so in order not to forget about it I've added it here :).

**Comment by antoniovazquezblanco** [comment]
Fixed
